name: Auto Release

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [main]
    paths:
      - 'src/main/java/**/Tags.java'   # 当 Tags.java 改动时自动触发

permissions:
  contents: write

jobs:
  release:
    uses: song682/workflows/.github/workflows/release-template.yml@main
    with:
      mod_archives_name: 'ModernStatistic'
      mc_version: '1.7.10'