name: Auto Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/main/java/**/Tags.java'

jobs:
  release:
    uses: song682/workflows/.github/workflows/release-template.yml@main
    with:
      mod_archives_name: 'ModernStatistic'
      mc_version: '1.7.10'
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      CURSEFORGE_PROJECT_ID: ${{ secrets.CURSEFORGE_PROJECT_ID }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      MODRINTH_PROJECT_ID: ${{ secrets.MODRINTH_PROJECT_ID }}
